from Accounts.AccountsAPI.AccountsSerializers.authors import AuthorSerializer, FullAuthorSerializer, ShortAuthorSerializer
from Accounts.AccountsAPI.AccountsSerializers.members import MemberSerializer, FullMemberSerializer, ShortMemberSerializer
from Accounts.AccountsAPI.AccountsSerializers.users import UserSerializer, GroupSerializer, UserRegistrationSerializer
from Accounts.AccountsAPI.AccountsSerializers.socialMediaHandles import SocialMediaHandleSerializer
from Accounts.AccountsAPI.AccountsSerializers.jwt_token_serializer import MyTokenObtainPairSerializer


