# Generated by Django 4.0.5 on 2022-09-05 16:27

import Articles.helpers.file_upload_config
import ckeditor.fields
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('reading_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=Articles.helpers.file_upload_config.thumbnail_config)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.author')),
                ('related_articles', models.ManyToManyField(blank=True, to='Articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('satisfaction', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Articles.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('SPAM_ADVERTISEMENT', 'a lot of spam advertisements.'), ('MISINFORMATION', 'misleading or misinformed information.'), ('HATE_SPEECH', 'hate speech and incites violence towards some social group.'), ('PORNOGRAPHIC', 'pornographic and sexual content.'), ('BULLY', 'bullying.'), ('TERRORISM', 'terroristic advocacy.'), ('SELF_INJURY', 'suicidal and self-harm content.'), ('HUMANITARIAN', 'humanitarian (or animal) abuse such as child abuse')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Articles.feedback')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('SPAM_ADVERTISEMENT', 'a lot of spam advertisements.'), ('MISINFORMATION', 'misleading or misinformed information.'), ('HATE_SPEECH', 'hate speech and incites violence towards some social group.'), ('PORNOGRAPHIC', 'pornographic and sexual content.'), ('BULLY', 'bullying.'), ('TERRORISM', 'terroristic advocacy.'), ('SELF_INJURY', 'suicidal and self-harm content.'), ('HUMANITARIAN', 'humanitarian (or animal) abuse such as child abuse')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.member')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Articles.tag'),
        ),
    ]
